name: emulator-test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: dummy-project
          install_components: 'beta'
      - name: Start Datastore Emulator
        run: |
          gcloud beta emulators datastore start --host-port=localhost:8010 --project=dummy-project &
          sleep 10
      - name: Set environment variables
        run: |
          echo "DATASTORE_EMULATOR_HOST=localhost:8010" >> $GITHUB_ENV
          echo "DATASTORE_PROJECT_ID=dummy-project" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
      - name: Seed Emulator
        run: python scripts/seed_emulator.py
      - name: Run tests
        run: pytest -q
